import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner/Banner";
import Navbar from "../components/NavBar/Navbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1> Netflix</h1>
      <Navbar />
      <Banner
        title="Clifford the red dog"
        subTitle="A very cute dog"
        imgUrl="static/clify.jpg"
      />
    </div>
  );
};

export default Home;
